
server:
 port: 8000

spring:
 application:
  name: RBAC_APPLICATION
 datasource:
  url: jdbc:oracle:thin:@localhost:1521:xe
  username: system
  password: root
  driver-class: oracle.jdbc.driver.OracleDriver
 jpa:
  hibernate:
   ddl-auto: update
  database-platform: org.hibernate.dialect.Oracle10gDialect
  show-sql: true
  
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/  
  